Codificación de variables categóricas
Codifique la siguiente variable categórica usando el método de codificación Ficticia. Incluya una columna de NaN para valores perdidos.

In [20]:
import pandas as pd
import numpy as np

aceros=['Corten','Corrugado','Galvanizado','Inoxidable','al Carbón']
precios=[(650,800),(600,700),(250,350),(2000,2500),(6000,6500)]

np.random.seed(123)
categórica=np.random.choice(aceros,size=50)
numérica=[]
for c in categórica:
  numérica.append(np.random.randint(*precios[aceros.index(c)]))
df=pd.DataFrame()
df['Precio']=numérica
df['Acero']=categórica

nans=np.random.randint(50,size=np.random.randint(5,10))
df.iloc[nans]=np.NaN

In [21]:
df.head(5)

   Precio        Acero
0   280.0  Galvanizado
1     NaN          NaN
2   320.0  Galvanizado
3   626.0    Corrugado
4  2208.0   Inoxidable

In [22]:
# Códificando la variable categorica "Acero" con el metodo de códficacion ficticia

df_dum = pd.get_dummies(df, dummy_na=True, prefix='', prefix_sep="")
df_dum.head(5)

   Precio  Corrugado  Corten  Galvanizado  Inoxidable  al Carbón  nan
0   280.0          0       0            1           0          0    0
1     NaN          0       0            0           0          0    1
2   320.0          0       0            1           0          0    0
3   626.0          1       0            0           0          0    0
4  2208.0          0       0            0           1          0    0

In [23]:
# unimos con el data frame original

df_with_dum = pd.concat([df, df_dum], axis=1)
df_with_dum.head(5)

,Precio,Acero,Precio,Corrugado,Corten,Galvanizado,Inoxidable,al Carbón,nan
0,280.0,Galvanizado,280.0,0,0,1,0,0,0
1,NaN,NaN,NaN,0,0,0,0,0,1
2,320.0,Galvanizado,320.0,0,0,1,0,0,0
3,626.0,Corrugado,626.0,1,0,0,0,0,0
4,2208.0,Inoxidable,2208.0,0,0,0,1,0,0